name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: save build
      uses: actions/upload-artifact@master
      with:
        name: my-build
        path: dist/entrevista

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: my-build
          path: dist/entrevista
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "dist/entrevista/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
        
